set -g mouse on

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind v split-window -v
bind h split-window -h

bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

new-session -s "coding"
split-window -v -p 20
attach-session -d
