#
# devices.conf
# Input device configurations
#

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = -1 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# OP1 8K mouse
device {
    name = endgame-gear-endgame-gear-op1-8k-v2-gaming-mouse
    sensitivity = -1
}
