#
# hyprland.conf
# Root hyprland config file
#

#
# Default programs
#
$terminal = uwsm app -- ghostty
$fileManager = uwsm app -- nautilus
$menu = uwsm app -- walker
$browser = uwsm app -- firefox

#
# Load in config files
#
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/devices.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/looks.conf
source = ~/.config/hypr/windowrules.conf

#
# Miscellaneous configs
#
ecosystem {
  enforce_permissions = 1
}
permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}
master {
    new_status = master
}
misc {
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}

