#
# keybinds.conf
# Keyboard shortcuts/bindings
#

$mainMod = SUPER # Sets "Super/Win/Cmd" key as main modifier

# Launchers
bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Space, exec, $menu
bind = $mainMod, E, exec, $fileManager
bind = $mainMod SHIFT, B, exec, $browser
bind = $mainMod SHIFT, E, exec, ~/.config/hypr/scripts/power.sh # Power menu
bind = $mainMod SHIFT, S, exec, grim -g "$(slurp)" - | wl-copy && notify-send "Screenshot" "Captured to clipboard" # 'Snipping Tool'

# Reload config, and 
bind = $mainMod SHIFT, C, exec, ~/.config/hypr/scripts/reload.sh

# Window management
bind = $mainMod, Q, killactive,
bind = $mainMod SHIFT, V, togglefloating,
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod SHIFT, Return, fullscreen, 1

# Move focus with mainMod+direction
bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r
bind = $mainMod, T, togglesplit, layoutmsg

# Move window with mainMod+shift+direction
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, J, movewindow, d
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, L, movewindow, r

bind = $mainMod, B, layoutmsg, preselect r
bind = $mainMod, V, layoutmsg, preselect d
bind = $mainMod SHIFT, F, togglefloating

# Toggle the current window into a group (or out of one)
bind = $mainMod, G, togglegroup 
bind = $mainMod, tab, changegroupactive, f # forward

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Resize windows with mouse
bindm = $mainMod, mouse:272, resizewindow
bindm = $mainMod, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF87AudioPrev, exec, playerctl previous

