#
# startup.conf
# Commands/applications to be run on startup
#

# non-uwsm startup apps
# exec-once = mako
# exec-once = ~/go/bin/elephant
# exec-once = ~/.cargo/bin/walker --gapplication-service
# exec-once = waybar
# exec-once = hyprpaper
# exec-once = sleep 2; hyperctl hyprpaper wallpaper ",~/dotfiles/wallpapers/fog.png"

# Suppress weird ibus notification at startup
exec-once = ibus-daemon -rxR --wayland

# uwsm startup apps
exec-once = uwsm finalize
# exec-once = uwsm app -- mako
exec-once = uwsm app -- elephant
exec-once = uwsm app -- walker --gapplication-service
exec-once = uwsm app -- waybar

