#
# startup.conf
# Commands/applications to be run on startup
#

# mako: Notification daemon
exec-once = mako

# elephant, walker: Helper backends for Walker application launcher
exec-once = elephant
exec-once = walker --gapplication-service

# waybar: Configurable status bar
exec-once = waybar

# hyprpaper: wallpaper
exec-once = hyprpaper
exec-once = sleep 2; hyprpaper wallpaper "~/Pictures/arch_nz.png"
