#
# windowrules.conf
# Useful window rules
#

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

# Audio device control
windowrule {
    name = pavucontrol
    match:class = ^(org.pulseaudio.pavucontrol)$
    float = on
    size = 500 800
    move = monitor_w-508 45
}

windowrule {
    name = imageviewer
    match:class = ^(com.github.aliencoweatcake.imageviewer)$
    float = on
    size = 1280 960
}

windowrule {
    name = glen
    match:title = ^(glen)$
    float = on
}

# Firefox windows shouldn't be _as_ transparent when unfocused
windowrule = opacity 1.0 0.95 override, match:class = ^firefox$

# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#     name = no-gaps-wtv1
#     match:float = false
#     match:workspace = w[tv1]
#
#     border_size = 0
#     rounding = 0
# }
#
# windowrule {
#     name = no-gaps-f1
#     match:float = false
#     match:workspace = f[1]
#
#     border_size = 0
#     rounding = 0
# }
